@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

imagePipeline(
  branchPattern: new BranchPattern(master: 'release/10.2.6', feature: '(?!^release/.*$)(^.*$)'),
  containers: ['container-registry.oracle.com/olcne/grafana:v10.2.6': 'olcne/grafana:v10.2.6'],
  platforms: ['ol9'],
  architectures: ['x86_64', 'aarch64'],
  yumOL9Repos: ['ol9_appstream'],
  buildScript: "sh olm/build-image.sh"
)
